### ISSUE TITLE
Java/JSS 10 build error

### ISSUE THREAD

**Issue by chrswk** [jrburke/r.js#995]
We are in the process of updating our environment to Java 10/11 from Java 8. But the r.js build step does not seem to work with the new JJS version we tried (10.0.2). We are running r.js version 2.3.6.

Is this a known problem or is there anything planned in regard to Java 10/11 support? Has anyone encountered a similar problem?

```
Exception in thread "main" java.lang.VerifyError: Code generation bug in "L:19#L:260#bind#L:385": likely stack misaligned: java.lang.NullPointerException src\main\resources\lib\r.js
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CodeGenerator.leaveFunctionNode(CodeGenerator.java:2183)
        at jdk.scripting.nashorn/jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405)
        at jdk.scripting.nashorn/jdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57)
        at jdk.scripting.nashorn/jdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47)
        at jdk.scripting.nashorn/jdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:635)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CompilationPhase.access$100(CompilationPhase.java:55)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CompilationPhase$BytecodeGenerationPhase.transform(CompilationPhase.java:424)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:631)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:657)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.CompiledFunction.handleRewriteException(CompiledFunction.java:847)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.CompiledFunction.handleRewriteException(CompiledFunction.java:739)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$173$11070AA$r.L:19#L:260#each(src\main\resources\lib\r.js:308)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$158$52289$r.L:19#L:260#newContext#enable(src\main\resources\lib\r.js:1365)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$228$70728A$r.L:19#L:260#newContext#enable-1(src\main\resources\lib\r.js:1809)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$225$52775AI$r.L:19#L:260#newContext#enable#L:1365(src\main\resources\lib\r.js:1413)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$300$13480AIA$r.L:19#L:260#bind#L:385(src\main\resources\lib\r.js:386)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$173$11070AA$r.L:19#L:260#each(src\main\resources\lib\r.js:308)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$158$52289$r.L:19#L:260#newContext#enable(src\main\resources\lib\r.js:1365)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$152$36710AAAA$r.L:19#L:260#newContext#init(src\main\resources\lib\r.js:1040)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$150$66350$r.L:19#L:260#newContext#makeRequire#localRequire#L:1701(src\main\resources\lib\r.js:1712)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$115$81564A$r.L:19#L:260#L:2068(src\main\resources\lib\r.js:2068)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$112$64232AAA$r.L:19#L:260#newContext#makeRequire#localRequire(src\main\resources\lib\r.js:1701)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$189$80019AAAA$r$cu1$restOf.L:19#L:260#requirejs(src\main\resources\lib\r.js:2049)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$176$728AAA$r$cu1$restOf.:scopeCall-41(src\main\resources\lib\r.js)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$176$728AAA$r$cu1$restOf.L:19(src\main\resources\lib\r.js:30374)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$84$r$cu1$restOf.:program(src\main\resources\lib\r.js:30432)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
        at jdk.scripting.nashorn/jdk.nashorn.tools.Shell.apply(Shell.java:519)
        at jdk.scripting.nashorn/jdk.nashorn.tools.Shell.runScripts(Shell.java:448)
        at jdk.scripting.nashorn/jdk.nashorn.tools.Shell.run(Shell.java:186)
        at jdk.scripting.nashorn.shell/jdk.nashorn.tools.jjs.Main.main(Main.java:104)
        at jdk.scripting.nashorn.shell/jdk.nashorn.tools.jjs.Main.main(Main.java:80)
Caused by: java.lang.NullPointerException
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CodeGenerator.generateContinuationHandler(CodeGenerator.java:5442)
        at jdk.scripting.nashorn/jdk.nashorn.internal.codegen.CodeGenerator.leaveFunctionNode(CodeGenerator.java:2165)
        ... 34 more
```

I could not find any useful information for this error, and line 385 that is mentioned in the stacktrace is just:

```
381 function bind(obj, fn) {
382     return function () {
383         return fn.apply(obj, arguments);
384     };
385 }
```

Thanks in advance.

**Comment by chrswk** [comment]
Since I just saw this [JEP](https://openjdk.java.net/jeps/335), I think we are going to switch to Node for our build...

**Comment by sam-ma** [comment]
As per [JDK-8222205](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8222205), the workaround is to execute with optimistic types disabled.

```
jjs -ot=false -scripting r.js -- -o test.config.js
```
